---
- name: Install ClusterHar Base Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - bridge-utils
    - wiringpi
    - screen
    - minicom

- name: Ensure we're going to do a text boot
  sudo: yes
  command: systemctl set-default multi-user.target

- name: More Configure the timezone
  sudo: yes
  file: src=/lib/systemd/system/getty@.service dest=/etc/systemd/system/getty.target.wants/getty@ttyGS0.service state=link force=yes backup=yes

- name: Get the cluster HAT software/config files
  sudo: yes
  get_url:
      url: http://dist.8086.net/clusterhat/clusterhat-files-latest.tgz
      dest: /root/clusterhat-files-latest.tgz

- name: Install cluster HAT software/config files
  sudo: yes
  unarchive:
      src: /root/clusterhat-files-latest.tgz
      dest: /
      extra_opts: ['C']

- name: Patch cluster Hat
  sudo: yes
  template: src=clusterhat.tpl dest=/sbin/clusterhat

- name: Configure network
  sudo: yes
  template: src=interfaces.tpl dest=/etc/network/interfaces

- name: Configure wpa supplicant
  sudo: yes
  template: src=wpa_supplicant.tpl dest=/etc/wpa_supplicant/wpa_supplicant.conf
