---
- name: Install ClusterHat Base Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - bridge-utils
    - wiringpi
    - screen
    - minicom
    - wget
    - tar
  register: clusterhat_package_installed

- name: Ensure we're going to do a text boot
  sudo: yes
  command: systemctl set-default multi-user.target
  register: clusterhat_text_boot_enabled

- name: Enable gadget mode
  sudo: yes
  file:
    src=/lib/systemd/system/getty@.service
    dest=/etc/systemd/system/getty.target.wants/getty@ttyGS0.service
    state=link
    force=yes
    backup=yes
  register: clusterhat_gadget_enable

- name: Install cluster HAT software/config files
  sudo: yes
  shell: "wget -O - --quiet http://dist.8086.net/clusterhat/clusterhat-files-latest.tgz | sudo tar -zxvC /"
  register: clusterhat_software_installed
  when: clusterhat_package_installed|success and clusterhat_text_boot_enabled|success and clusterhat_gadget_enable|success

- name: Patch cluster Hat
  sudo: yes
  template: src=clusterhat.tpl dest=/sbin/clusterhat
  register: clusterhat_patched
  when: clusterhat_software_installed|success

- name: Configure network
  sudo: yes
  template: src=interfaces.tpl dest=/etc/network/interfaces
  register: clusterhat_network_bridge_installed
  when: clusterhat_patched|success
  notify:
    - network-reloaded

- name: Install Cluster service
  sudo: yes
  template: src=clusterhat.service.tpl dest=/etc/systemd/system/clusterhat.service
  register: clusterhat_service
  when: clusterhat_patched|success

- name: Enable Cluster service
  sudo: yes
  service: name=clusterhat enabled=yes
  register: clusterhat_enable
  when: clusterhat_service|success