---
- name: Install Docker-compose
  become: yes
  pip:
    name: docker-compose
    state: present
    version: 1.9
  register: docker_compose_installed

- name: PHP Arm Service on Docker
  become: yes
  docker_service:
    project_name: "php-arm-service"
    definition:
      "php-arm-service":
        image: "teknoo/php7-rpi"
        privileged: true
        volumes:
          - "{{ php_arm_service.volume_path_host }}:{{ php_arm_service.volume_path_container }}"
    scale:
      "php-arm-service": "{{ dhcp_server.static_map|length + 1 }}"
  when: docker_compose_installed|success
  register: php_arm_service
