---
- hosts: host.ssh
  become: true
  vars_files:
    - vars/all.yml
    - vars/host.yml
  roles:
    - base
    - shorewall
    - clusterhat
    - ntp-server
    - nfs-server
    - dhcp-server
    - docker
    - php-arm-docker
    - docker-swarm-manager
    - php-arm-service
