---
- name: Configure network
  become: yes
  template: src=interfaces.tpl dest=/etc/network/interfaces
  register: network_client_configured

- name: Configure ntp
  become: yes
  template: src=ntp.conf.tpl dest=/etc/ntp.conf
  register: network_client_ntp

- name: Config SSH for Pi User
  become: no
  template: src=ssh_config.tpl dest=/home/pi/.ssh/config
