---
- name: Prepare tmp directory
  sudo: yes
  file: path=/tmp/php-docker state=directory
  register: php_arm_docker_tmp_dir

- name: Transfert Dockerfile
  sudo: yes
  template: src=Dockerfile.tpl dest=/tmp/php-docker/Dockerfile
  register: php_arm_docker_dockerfile
  when: php_arm_docker_tmp_dir|success

- name: Update Export file
  sudo: yes
  template: src=docker.ini.tpl dest=/tmp/php-docker/docker.ini
  register: php_arm_docker_docker_ini
  when: php_arm_docker_tmp_dir|success

- name: Build PHP Container
  sudo: yes
  docker_image:
    path: /tmp/php-docker
    name: php7-rpi
  register: php_arm_docker_built
  when: php_arm_docker_dockerfile|success and php_arm_docker_tmp_dir|success
