---
- name: Install Docker-py
  become: yes
  pip:
    name: docker-py
    state: latest
  register: docker_py_installed

- name: Prepare tmp directory
  become: yes
  file: path=/tmp/php-docker state=directory
  register: php_arm_docker_tmp_dir

- name: Transfert Dockerfile
  become: yes
  template: src=Dockerfile.tpl dest=/tmp/php-docker/Dockerfile
  register: php_arm_docker_dockerfile
  when: php_arm_docker_tmp_dir|success

- name: Update Export file
  become: yes
  template: src=docker.ini.tpl dest=/tmp/php-docker/docker.ini
  register: php_arm_docker_docker_ini
  when: docker_py_installed|success and php_arm_docker_tmp_dir|success

- name: Update Command file
  become: yes
  template: src=command.sh.tpl dest=/tmp/php-docker/command.sh
  register: php_arm_docker_docker_command
  when: docker_py_installed|success and php_arm_docker_tmp_dir|success

- name: Build PHP Container
  become: yes
  docker_image:
    path: /tmp/php-docker
    name: teknoo-php7-rpi
  register: php_arm_docker_built
  when: php_arm_docker_dockerfile|success and php_arm_docker_tmp_dir|success
