---
- name: Install NFS Client
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - nfs-common
  register: nfs_client_installed

- name: Creates mnt data directory
  become: yes
  file: path={{shared_storage.nfs_mount_point}} state=directory
  register: nfs_client_mount_point
  when: nfs_client_installed|success

- name: Update FSTAB
  become: yes
  mount:
    name: "{{shared_storage.nfs_mount_point}}"
    src: "{{network.host_address}}:{{shared_storage.disk_mount_point}}"
    fstype: nfs
    opts: rw
    state: mounted
  register: nfs_client_configured
  when: nfs_client_mount_point|success
