---
- name: Update apt
  become: yes
  apt: update_cache=yes
  register: base_apt_updated

- name: Upgrade apt
  become: yes
  apt: upgrade=dist
  register: base_apt_upgrated
  when: base_apt_updated|success

- name: Install System Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - ssh
    - screen
    - wget
    - python
    - python-software-properties
    - python-setuptools
    - openssl
  register: base_system_installed
  when: base_apt_updated|success

- name: Install pip
  become: yes
  easy_install:
    name: pip
    state: latest
  register: pip_installed
  when: base_system_installed|success

- name: Install Extra Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: server.packages
  register: base_system_extra_installed
  when: server.packages is defined and base_apt_updated|success

- name: Configure the timezone
  become: yes
  template: src=timezone.tpl dest=/etc/timezone
  register: base_timezone_defined

- name: More Configure the timezone
  become: yes
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes
  register: base_locale_linked
  when: base_timezone_defined|success

- name: Set default system language pack
  shell: locale-gen {{server.locale}}
  become: yes
  register: base_locale_generated
  when: base_timezone_defined|success

- name: Set authorized key from current user
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  register: ssh_authorized_key

- name: Set authorized key from ssh cluster key
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', 'ssh/id_rsa.pub') }}"
  register: cluster_ssh_authorized_key

- name: copy private ssh cluster key
  copy:
    src: "ssh/id_rsa"
    dest: "/home/pi/.ssh/id_rsa"
    directory_mode: true
    mode: "u=rwx,g=,o="
  register: cluster_ssh_private_key

- name: copy public ssh cluster key
  copy:
    src: "ssh/id_rsa.pub"
    dest: "/home/pi/.ssh/id_rsa.pub"
    directory_mode: true
    mode: "u=rwx,g=,o="
  register: cluster_ssh_pub_key