---
- name: Determine swarm status
  shell: >
    docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: docker_swarm_status

- name: Initialize swarm cluster
  shell: >
    docker swarm init
    --advertise-addr={{ network.host_address }}
  when: "'active' not in docker_swarm_status.stdout_lines"
  register: docker_swarm_init

- name: Add host to swarm_manager_operational group
  add_host:
    hostname: "{{ play_hosts[0] }}"
    groups: swarm_manager_operational

- name: Retrieve swarm manager token
  shell: docker swarm join-token -q manager
  register: docker_swarm_manager_token

- name: Retrieve swarm worker token
  shell: docker swarm join-token -q worker
  register: docker_swarm_worker_token
